# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invited_to_family_dinner', models.BooleanField(default=False)),
                ('invited_to_friends_dinner', models.BooleanField(default=False)),
                ('attending_family_dinner', models.NullBooleanField()),
                ('attending_friends_dinner', models.NullBooleanField()),
                ('attending_wedding', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('has_plusone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='meal_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invites.MealOption'),
        ),
    ]
