# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invites.Invite'),
            preserve_default=False,
        ),
    ]
